on: push
name: CI

jobs:
  publish-release:
    name: Publish release
    #needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
      - name: Fetch release archives
        uses: actions/download-artifact@v2
      - name: Get the tag name
        id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - name: Create github release
        uses: MinerGreggy/github-actions/publish-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --name Flora-Dashboard-Satellite
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'release-archive-*/*.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.tag.outputs.TAG }}