
name: npm-publish

on:
  push:
    branches:
      - main # Change this to your default branch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: flood-io/is-published-on-npm@v1
        id: is-published
      - name: Release
        if: ${{ steps.is-published.outputs.published == 'false' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.is-published.outputs.version }}
          release_name: Release ${{ steps.is-published.outputs.version }}
          draft: false
          prerelease: false
  publish-to-npm:
    name: publish-to-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with:
          version: 12
          registry-url: 'https://registry.npmjs.org'
      - uses: shawnbot/npm-publish-action@master
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           # NOTE: use the NODE_ prefix instead of NPM_ here!
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
